version: '3.8'
services:
  postgres:
    container_name: postgres_auth
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: deno
      POSTGRES_PASSWORD: deno
      POSTGRES_DB: deno
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: